#!/bin/bash
set -e
cd ../common
./gen-test-cases.clj
cd -
# override fennel command
FENNEL_PATH="cljlib/?/init.fnl;$FENNEL_PATH" LUA_PATH="cljlib/?/init.lua;json-lua/?.lua;$LUA_PATH" PATH=.:$PATH ./fennel-test/runner test/midi-editor/notation-tests.fnl test/midi-editor/drum-notation/rep-test.fnl test/midi-editor/drum-notation/solve-test.fnl test/midi-editor/drum-notation/test-helpers-test.fnl
