#!/bin/bash
set -e
cd cljlib
make
cd ..
cd ../common
./gen-test-cases.clj
cd ../fnl
# override fennel command
PATH=.:$PATH ./fennel-test/runner test/midi-editor/notation-tests.fnl test/midi-editor/drum-notation/rep-test.fnl test/midi-editor/drum-notation/solve-test.fnl test/midi-editor/drum-notation/test-helpers-test.fnl
