name: check
on: [push, pull_request]
jobs:
  reapack-index:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Pandoc
      run:  sudo apt-get install -yy pandoc
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - name: Install reapack-index
      run:  gem install reapack-index
    - name: Validate packages
      run:  reapack-index --check
    - name: Install Lua
      uses: leafo/gh-actions-lua@v10
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@master
      with:
        lein: latest
        bb: latest
    - run: ./run-tests
