name: check
on: [push, pull_request]
jobs:
  reapack-index:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repository
      uses: actions/checkout@v3
    - name: Install Pandoc
      run:  sudo apt-get install -yy pandoc
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - name: Install reapack-index
      run:  gem install reapack-index
    - name: Validate packages
      run:  reapack-index --check
    - name: Install Lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.3"
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@10.2
      with:
        lein: 2.9.8
        bb: 1.2.174
    - run: ./run-tests
